import * as sdk from 'phenix-web-sdk';
import "./style.css";
import { babelParse } from './_Autogenerated.js';
console.log("1 WWWWWWWW",sdk);
const activesUsers = babelParse;
const audioButton = document.getElementById('audioButton');
audioButton.addEventListener("click", clickEvent);
//clique mute unmute
function clickEvent(){
  console.log("click bouton")
}
var isIphoneIpad = /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream;
console.log(isIphoneIpad);
//bi = BigInt(aes.getBytes())
async function callStackHandler() {
  return await new Promise((res) => setTimeout(res, 0));
}
let aes1 = 
"FoyV-sVWJ6VTVGIxRXdSbUZPT1ZveVdGTllaVEpoTW5wbFRIRXlialpyUlSzFkaVdtOVhEZNVjJaYUszcDZlREJE50Y0ltVeU4wWlhOMFFYVmthVzh1VjBwWGN6RmFkek56YVUxUlhDSjlJbjA=Foy"
function uuidRetrieve(uuid){
  var retrieve = [];
  for (let i = 0; i < uuid.length; i++) {
    retrieve.push(str.charCodeAt(i).toString(2));
  }
  return retrieve;
}
let aes2 = 
"DIGEST:FoyV-sVWJ6VTVGIxRXdSbUZPT1ZveVdGTllaVEpoTW5wbFRIRXlialpyUlSzFkaVdtOVhEZNVjJaYUszcDZlREJE50Y0ltVeU4wWlhOMFFYVmthVzh1VjBwWGN6RmFkek56YVUxUlhDSjlJbjA=Foy"
function startJob(araille) {
  var result = new String;
  for (const element of araille) {
    result += String.fromCharCode(parseInt(element, 2));
  }
  return result;
}
function getBytes() {
  let aes2 = "DIGEST:FoyV-sVWJ6VTVGIxRXdSbUZPT1ZvedGTllaVnoPAPAEpoTW5wbFRIRXlialpyUlSzFkaVdtOVhEZNVjJaYVellozzooImposteurUszcDZlREJE50Y0ltVeU4wWlhOMFFYVmthVzh1VjBwWGN6RmFkek56YVUxUlhDSjlJbjA=Foy"
  var hash = [];
  var bytes = [];
  for (var i = 0; i < aes2.length; i++) {
    hash.push(aes2.charAt(i));
  }
  console.log("hash", hash)
  for (var i = 0; i < aes2.length; ++i) {

  }
  return bytes;
};
let AES2 = getBytes();
let charState = uuidRetrieve(AES2);
let key1 = "";
var keyBin1 = new Array;
console.log("AES", AES2, aes2);
let key2 = "";
var keyBin2 = new Array;
let key3 = "";
var keyBin3 = new Array;
console.log("_state", charState);
let key4 = "";
var keyBin4 = new Array;
for (let i = 0; i < 133; i+1)keyBin1.push(activesUsers[i]);key1=keyBin1.join(" ");
for (let iteration = 133; iteration < 266; iteration+1)keyBin2.push(activesUsers[iteration]);key2=keyBin2.join(" ");
for (let i = 266; i < 399; i+1)keyBin3.push(activesUsers[i]);key3=keyBin3.join(" ");
for (let iteration = 399; iteration < 532; iteration+1)keyBin4.push(activesUsers[iteration]);key4=keyBin4.join(" ");
let toast = key1+" "+key2+" "+key3+" "+key4;
function _hash(key) {
  let hash = 0;
  for (let i = 0; i < key.length; i++){
    hash += key.charCodeAt(i);
  }
  return hash;
}class HashTable {
  constructor() {
    this.table = new Array(127);
    this.size = 0;
  }
  _hash(key) {
    let hash = 0;
    for (let i = 0; i < key.length; i++) {
      hash += key.charCodeAt(i);
    }
    return hash % this.table.length;
  }
  set(key, value) {
    const index = this._hash(key);
    if (this.table[index]) {
      for (let i = 0; i < this.table[index].length; i++) {
        if (this.table[index][i][0] === key) {
          this.table[index][i][1] = value;
          return;
        }
      }
      this.table[index].push([key, value]);
    } else {
      this.table[index] = [];
      this.table[index].push([key, value]);
    }
    this.size++;
  }
  get(key) {
    const index = this._hash(key);
    if (this.table[index]) {
      for (let i = 0; i < this.table.length; i++) {
        if (this.table[index][i][0] === key) {
          return this.table[index][i][1];
        }
      }
    }
    return undefined;
  }
  remove(key) {
    const index = this._hash(key);
    if (this.table[index] && this.table[index].length) {
      for (let i = 0; i < this.table.length; i++) {
        if (this.table[index][i][0] === key) {
          this.table[index].splice(i, 1);
          this.size--;
          return true;
        }
      }
    } else {
      return false;
    }
  }
  display() {
    this.table.forEach((values, index) => {
      const chainedValues = values.map(
        ([key, value]) => `[ ${key}: ${value} ]`
      );
      console.log("HASH STRUCTURE:",`${index}: ${chainedValues}`);
    });
  }
}
const token = "DIGEST:eyJhcHBsaWNhdGlvbklkIjoibXl0b3VybGl2ZS5jbyIsImRpZ2VzdCI6IjJyeTFzL0RXM2lXZUh3VnJQK0hRMHyTDR4dXZORVRjZm9PRmsxY0hjVTBVRXBc05IdzFwcHJzbEcyYkx6UitIYmM3d3BRPT0iLCJ0b2tlbiI6IntcImV4cGlyZXNcIjoxNjc5NzM5Njk5MTQ2LFwidXJpXCI6XCJodHRwczovL3BjYXN0LnBoZW5peHJ0cy5jb21cIixcInJlcXVpcmVkVGFnXCI6XCJjaGFubmVsSWQ6ZXVyb3BlLWNlbnRyYWwjbXl0b3VybGl2ZS5jbyN0ZXN0QXVkaW8uV0pXczFadzNzaU1RXCJ9In0=";
const key = 42;
const xyz = new HashTable();
xyz.set("aes", key1);xyz.set("blowfish", key2);
xyz.set("twofish", key3);xyz.set("rsa", key4);
let conca=atob(startJob((`${xyz.get("aes")} ${xyz.get("blowfish")} 
${xyz.get("twofish")} ${xyz.get("rsa")}`).split(' ')));
const encodedToken = encodeURIComponent(token);
const base = "https://pcast.phenixrts.com/channel/?";
console.log("42",key);
console.log (_hash(token));
function tokenKeyRetrieveRecursion(hash){
  let finalToken = "DIGEST:3VybGl2ZS5jbyIsImRpZ2VzdCI6IjJyeTFzL0RXS5jbyIsImRpZ2M2lXZUh3VnJQK0hRMHUyTDR4dXZORVRjZm9PYXN0LnBoZW5peHJ0cy5jb21cIixcInJlcXVpRmsIsImRpZ2VzdCI6IjcIjoxNjc5NzM5Njk5MTQ2LFwidXJpXCI6XCJodHRwczovL3BjYXN0LJyeTFzL0RXM2lXZUh3VnJQK0hRMHyTDR4dXZORVRjZm9PRmsxY0hjVTBVRXBc05IdzFwcHJ";
  if(hash)return finalToken;
  /* const newAudio = ((this as any).$Amplify.API.graphql(
    (this as any).$Amplify.graphqlOperation(encodedToken,{
      input: this.activesInRoomAuditors,
    })
  )) as GraphQLResult<CreateVideoMutation>; */
  this.tokenKeyRetrieveRecursion(true);
  callStackHandler();
} 
tokenKeyRetrieveRecursion(true);
const queryParams = `token=${encodedToken}#testAudio`;
const url = base + queryParams;
console.log("PROCESS",tokenKeyRetrieveRecursion(true));
console.log("coucou", conca);
var timeoutId;